"""Backend-independent MCP catalog shared by the server, CLI, and documentation.

Effective defaults describe omitted server arguments, not values injected by the
client. Keep them aligned with handlers; registry tests verify this contract.
"""

from __future__ import annotations

from typing import Any


def _tool(
    name: str,
    description: str,
    properties: dict[str, Any] | None = None,
    required: list[str] | None = None,
    schema_extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    input_schema: dict[str, Any] = {
        "type": "object",
        "properties": properties or {},
    }
    if required:
        input_schema["required"] = required
    if schema_extra:
        input_schema.update(schema_extra)

    return {
        "name": name,
        "description": description,
        "inputSchema": input_schema,
    }


def _definitions() -> list[dict[str, Any]]:
    return [
        _tool("health.ping", "Health check."),
        _tool(
            "mcp.response_format",
            "Explain MCP tool result fields (`structuredContent` full payload, "
            "`content[0].text` summary).",
        ),
        _tool("binja.info", "Return Binary Ninja version/install info."),
        _tool(
            "binja.call",
            "Generic API bridge: call `bn.*` or `bv.*` target path.",
            {
                "target": {"type": "string"},
                "session_id": {"type": "string"},
                "args": {"type": "array", "items": {}},
                "kwargs": {"type": "object"},
            },
            ["target"],
        ),
        _tool(
            "binja.eval",
            "Evaluate Python code with `bn`, `sessions`, and optional `bv`.",
            {
                "code": {"type": "string"},
                "session_id": {"type": "string"},
            },
            ["code"],
        ),
        _tool(
            "session.open",
            "Open a binary and create a session.",
            {
                "path": {"type": "string"},
                "update_analysis": {"type": "boolean"},
                "options": {"type": "object"},
                "read_only": {"type": "boolean"},
                "deterministic": {"type": "boolean"},
            },
            ["path"],
        ),
        _tool(
            "session.open_bytes",
            "Open a binary session from base64-encoded bytes.",
            {
                "data_base64": {"type": "string"},
                "filename": {"type": "string"},
                "update_analysis": {"type": "boolean"},
                "options": {"type": "object"},
                "read_only": {"type": "boolean"},
                "deterministic": {"type": "boolean"},
            },
            ["data_base64"],
        ),
        _tool(
            "session.open_existing",
            "Open another session from an existing session's file.",
            {
                "source_session_id": {"type": "string"},
                "update_analysis": {"type": "boolean"},
                "options": {"type": "object"},
                "read_only": {"type": "boolean"},
                "deterministic": {"type": "boolean"},
            },
            ["source_session_id"],
        ),
        _tool(
            "session.close",
            "Close one open session.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool("session.list", "List open sessions."),
        _tool(
            "session.mode",
            "Get session safety/determinism mode.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "session.set_mode",
            "Update session safety/determinism mode.",
            {
                "session_id": {"type": "string"},
                "read_only": {"type": "boolean"},
                "deterministic": {"type": "boolean"},
            },
            ["session_id"],
        ),
        _tool(
            "analysis.status",
            "Get lifecycle status, timestamps, task and error, plus native state/progress.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "analysis.progress",
            "Get analysis progress snapshot.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "analysis.update",
            "Start tracked analysis and return task_id; reject overlap on this session.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "analysis.update_and_wait",
            "Wait synchronously until analysis finishes; no timed partial-success response.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "analysis.abort",
            "Abort analysis.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "analysis.set_hold",
            "Hold/release analysis queue.",
            {
                "session_id": {"type": "string"},
                "hold": {"type": "boolean"},
            },
            ["session_id", "hold"],
        ),
        _tool(
            "binary.summary",
            "Get binary/session summary.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "binary.save",
            "Save the current binary view to a file path.",
            {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
            },
            ["session_id", "path"],
        ),
        _tool(
            "binary.functions",
            "List functions with pagination.",
            {
                "session_id": {"type": "string"},
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id"],
        ),
        _tool(
            "binary.strings",
            "List discovered strings with pagination.",
            {
                "session_id": {"type": "string"},
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id"],
        ),
        _tool(
            "binary.search_text",
            "Search raw text/bytes in a session.",
            {
                "session_id": {"type": "string"},
                "query": {"type": "string"},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "query"],
        ),
        _tool(
            "binary.sections",
            "List sections with pagination.",
            {
                "session_id": {"type": "string"},
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id"],
        ),
        _tool(
            "binary.segments",
            "List segments with pagination.",
            {
                "session_id": {"type": "string"},
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id"],
        ),
        _tool(
            "binary.symbols",
            "List symbols with pagination.",
            {
                "session_id": {"type": "string"},
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id"],
        ),
        _tool(
            "binary.data_vars",
            "List data variables with pagination.",
            {
                "session_id": {"type": "string"},
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id"],
        ),
        _tool(
            "binary.get_function_at",
            "Find function by address.",
            {
                "session_id": {"type": "string"},
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
            },
            ["session_id", "address"],
        ),
        _tool(
            "binary.get_function_disassembly_at",
            "Get full disassembly for the function containing an address.",
            {
                "session_id": {"type": "string"},
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
            },
            ["session_id", "address"],
        ),
        _tool(
            "binary.get_function_il_at",
            "Get full IL for the function containing an address.",
            {
                "session_id": {"type": "string"},
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "level": {"type": "string", "enum": ["llil", "mlil", "hlil"]},
                "ssa": {"type": "boolean"},
            },
            ["session_id", "address"],
        ),
        _tool(
            "binary.functions_at",
            "List functions at an address.",
            {
                "session_id": {"type": "string"},
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
            },
            ["session_id", "address"],
        ),
        _tool(
            "binary.basic_blocks_at",
            "List basic blocks at an address with pagination.",
            {
                "session_id": {"type": "string"},
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "address"],
        ),
        _tool(
            "function.basic_blocks",
            "List basic blocks in a function with pagination.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "function_start"],
        ),
        _tool(
            "disasm.linear",
            "Get linear disassembly lines.",
            {
                "session_id": {"type": "string"},
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id"],
        ),
        _tool(
            "search.data",
            "Search for raw byte patterns (hex string).",
            {
                "session_id": {"type": "string"},
                "data_hex": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "data_hex"],
        ),
        _tool(
            "search.next_text",
            "Find next text match.",
            {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "query": {"type": "string"},
            },
            ["session_id", "start", "query"],
        ),
        _tool(
            "search.all_text",
            "Find all text matches in range (regex optional).",
            {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "query": {"type": "string"},
                "regex": {"type": "boolean"},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "start", "end", "query"],
        ),
        _tool(
            "search.next_data",
            "Find next data/byte-pattern match.",
            {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "data_hex": {"type": "string"},
            },
            ["session_id", "start", "data_hex"],
        ),
        _tool(
            "search.all_data",
            "Find all data/byte-pattern matches in range.",
            {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "data_hex": {"type": "string"},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "start", "end", "data_hex"],
        ),
        _tool(
            "search.next_constant",
            "Find next constant occurrence.",
            {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "constant": {"type": "integer"},
            },
            ["session_id", "start", "constant"],
        ),
        _tool(
            "search.all_constant",
            "Find all constant occurrences in range.",
            {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "constant": {"type": "integer"},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "start", "end", "constant"],
        ),
        _tool(
            "xref.code_refs_to",
            "Code references to an address.",
            {
                "session_id": {"type": "string"},
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "address"],
        ),
        _tool(
            "xref.code_refs_from",
            "Code references from an address.",
            {
                "session_id": {"type": "string"},
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "length": {"type": "integer", "minimum": 1},
            },
            ["session_id", "address"],
        ),
        _tool(
            "xref.data_refs_to",
            "Data references to an address.",
            {
                "session_id": {"type": "string"},
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "address"],
        ),
        _tool(
            "xref.data_refs_from",
            "Data references from an address.",
            {
                "session_id": {"type": "string"},
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "length": {"type": "integer", "minimum": 1},
            },
            ["session_id", "address"],
        ),
        _tool(
            "function.callers",
            "Callers of a function.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
            },
            ["session_id", "function_start"],
        ),
        _tool(
            "function.callees",
            "Callees of a function.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
            },
            ["session_id", "function_start"],
        ),
        _tool(
            "function.variables",
            "List function variables.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
            },
            ["session_id", "function_start"],
        ),
        _tool(
            "function.var_refs",
            "List variable references in MLIL/HLIL.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "variable_name": {"type": "string"},
                "level": {"type": "string", "enum": ["mlil", "hlil"]},
            },
            ["session_id", "function_start", "variable_name"],
        ),
        _tool(
            "function.var_refs_from",
            "List variable references originating from an address.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "level": {"type": "string", "enum": ["mlil", "hlil"]},
                "length": {"type": "integer", "minimum": 1},
            },
            ["session_id", "function_start", "address"],
        ),
        _tool(
            "function.ssa_var_def_use",
            "Get SSA variable definition and uses.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "variable_name": {"type": "string"},
                "version": {"type": "integer", "minimum": 0},
                "level": {"type": "string", "enum": ["mlil", "hlil"]},
            },
            ["session_id", "function_start", "variable_name", "version"],
        ),
        _tool(
            "function.ssa_memory_def_use",
            "Get SSA memory definition and uses by memory version.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "version": {"type": "integer", "minimum": 0},
                "level": {"type": "string", "enum": ["mlil", "hlil"]},
            },
            ["session_id", "function_start", "version"],
        ),
        _tool(
            "value.reg",
            "Get register value at/after an address.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "register": {"type": "string"},
                "after": {"type": "boolean"},
            },
            ["session_id", "function_start", "address", "register"],
        ),
        _tool(
            "value.stack",
            "Get stack contents at/after an address.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "stack_offset": {"type": "integer"},
                "size": {"type": "integer", "minimum": 1},
                "after": {"type": "boolean"},
            },
            ["session_id", "function_start", "address", "stack_offset", "size"],
        ),
        _tool(
            "value.possible",
            "Get IL possible value set at an address.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "level": {"type": "string", "enum": ["llil", "mlil", "hlil"]},
                "ssa": {"type": "boolean"},
            },
            ["session_id", "function_start", "address"],
        ),
        _tool(
            "value.flags_at",
            "Get lifted IL flag read/write state at an address.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            ["session_id", "function_start", "address"],
        ),
        _tool(
            "memory.read",
            "Read bytes from the view.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer", "minimum": 1, "maximum": 65536},
            },
            ["session_id", "address", "length"],
        ),
        _tool(
            "memory.write",
            "Write bytes (hex) to the view.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "data_hex": {"type": "string"},
            },
            ["session_id", "address", "data_hex"],
        ),
        _tool(
            "memory.insert",
            "Insert bytes (hex) into the view.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "data_hex": {"type": "string"},
            },
            ["session_id", "address", "data_hex"],
        ),
        _tool(
            "memory.remove",
            "Remove bytes from the view.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer", "minimum": 1},
            },
            ["session_id", "address", "length"],
        ),
        _tool(
            "memory.reader_read",
            "Read integer values via BinaryReader.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "width": {"type": "integer", "enum": [1, 2, 4, 8]},
                "endian": {"type": "string", "enum": ["little", "big"]},
            },
            ["session_id", "address", "width"],
        ),
        _tool(
            "memory.writer_write",
            "Write integer values via BinaryWriter.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "width": {"type": "integer", "enum": [1, 2, 4, 8]},
                "value": {"type": "integer"},
                "endian": {"type": "string", "enum": ["little", "big"]},
            },
            ["session_id", "address", "width", "value"],
        ),
        _tool(
            "data.typed_at",
            "Get typed data variable at an address.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            ["session_id", "address"],
        ),
        _tool(
            "disasm.function",
            "Get full disassembly for the function containing an address.",
            {
                "session_id": {"type": "string"},
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
            },
            ["session_id", "address"],
        ),
        _tool(
            "disasm.range",
            "Address-range disassembly lines.",
            {
                "session_id": {"type": "string"},
                "start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "length": {"type": "integer", "minimum": 1},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "start", "length"],
        ),
        _tool(
            "il.function",
            "IL function listing.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "level": {"type": "string", "enum": ["llil", "mlil", "hlil"]},
                "ssa": {"type": "boolean"},
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "function_start"],
        ),
        _tool(
            "il.instruction_by_addr",
            "Get IL instruction by source address.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "level": {"type": "string", "enum": ["llil", "mlil", "hlil"]},
                "ssa": {"type": "boolean"},
            },
            ["session_id", "function_start", "address"],
        ),
        _tool(
            "il.address_to_index",
            "Map address to IL index/indices.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "address": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "level": {"type": "string", "enum": ["llil", "mlil", "hlil"]},
                "ssa": {"type": "boolean"},
            },
            ["session_id", "function_start", "address"],
        ),
        _tool(
            "il.index_to_address",
            "Map IL index to source address.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "index": {"type": "integer", "minimum": 0},
                "level": {"type": "string", "enum": ["llil", "mlil", "hlil"]},
                "ssa": {"type": "boolean"},
            },
            ["session_id", "function_start", "index"],
        ),
        _tool(
            "annotation.rename_function",
            "Rename a function.",
            {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "new_name": {"type": "string"},
            },
            ["session_id", "function_start", "new_name"],
        ),
        _tool(
            "annotation.rename_symbol",
            "Rename symbol at address.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "new_name": {"type": "string"},
            },
            ["session_id", "address", "new_name"],
        ),
        _tool(
            "annotation.undefine_symbol",
            "Undefine user symbol at address.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            ["session_id", "address"],
        ),
        _tool(
            "annotation.define_symbol",
            "Define symbol at address.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "symbol_type": {"type": "string"},
            },
            ["session_id", "address", "name"],
        ),
        _tool(
            "annotation.rename_data_var",
            "Rename data variable.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "new_name": {"type": "string"},
            },
            ["session_id", "address", "new_name"],
        ),
        _tool(
            "annotation.define_data_var",
            "Define data variable.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "type_name": {"type": "string"},
                "width": {"type": "integer", "minimum": 1},
                "name": {"type": "string"},
            },
            ["session_id", "address"],
        ),
        _tool(
            "annotation.undefine_data_var",
            "Undefine data variable.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            ["session_id", "address"],
        ),
        _tool(
            "annotation.set_comment",
            "Set comment at address.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "comment": {"type": "string"},
            },
            ["session_id", "address", "comment"],
        ),
        _tool(
            "annotation.get_comment",
            "Get comment at address.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            ["session_id", "address"],
        ),
        _tool(
            "annotation.add_tag",
            "Add user data tag at address.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "tag_type": {"type": "string"},
                "data": {"type": "string"},
                "icon": {"type": "string"},
            },
            ["session_id", "address", "tag_type", "data"],
        ),
        _tool(
            "annotation.get_tags",
            "Get tags at address.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            ["session_id", "address"],
        ),
        _tool(
            "metadata.store",
            "Store metadata by key.",
            {
                "session_id": {"type": "string"},
                "key": {"type": "string"},
                "value": {},
            },
            ["session_id", "key", "value"],
        ),
        _tool(
            "metadata.query",
            "Query metadata by key.",
            {
                "session_id": {"type": "string"},
                "key": {"type": "string"},
            },
            ["session_id", "key"],
        ),
        _tool(
            "metadata.remove",
            "Remove metadata by key.",
            {
                "session_id": {"type": "string"},
                "key": {"type": "string"},
            },
            ["session_id", "key"],
        ),
        _tool(
            "function.metadata_store",
            "Store function metadata by key.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "key": {"type": "string"},
                "value": {},
            },
            ["session_id", "function_start", "key", "value"],
        ),
        _tool(
            "function.metadata_query",
            "Query function metadata by key.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "key": {"type": "string"},
            },
            ["session_id", "function_start", "key"],
        ),
        _tool(
            "function.metadata_remove",
            "Remove function metadata by key.",
            {
                "session_id": {"type": "string"},
                "function_start": {
                    "oneOf": [{"type": "integer"}, {"type": "string"}],
                },
                "key": {"type": "string"},
            },
            ["session_id", "function_start", "key"],
        ),
        _tool(
            "patch.assemble",
            "Assemble and patch instruction bytes at address.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "asm": {"type": "string"},
            },
            ["session_id", "address", "asm"],
        ),
        _tool(
            "patch.status",
            "Inspect patch availability at address.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            ["session_id", "address"],
        ),
        _tool(
            "patch.convert_to_nop",
            "Patch instruction to NOP when supported.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            ["session_id", "address"],
        ),
        _tool(
            "patch.always_branch",
            "Patch conditional branch to always branch when supported.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            ["session_id", "address"],
        ),
        _tool(
            "patch.never_branch",
            "Patch conditional branch to never branch when supported.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            ["session_id", "address"],
        ),
        _tool(
            "patch.invert_branch",
            "Patch conditional branch by inversion when supported.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            ["session_id", "address"],
        ),
        _tool(
            "patch.skip_and_return_value",
            "Patch instruction to skip and return value when supported.",
            {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "value": {"type": "integer"},
            },
            ["session_id", "address", "value"],
        ),
        _tool(
            "undo.begin",
            "Begin undo transaction.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "undo.commit",
            "Commit undo transaction.",
            {
                "session_id": {"type": "string"},
                "transaction_id": {"type": "string"},
            },
            ["session_id"],
        ),
        _tool(
            "undo.revert",
            "Revert undo transaction.",
            {
                "session_id": {"type": "string"},
                "transaction_id": {"type": "string"},
            },
            ["session_id"],
        ),
        _tool(
            "undo.undo",
            "Perform undo.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "undo.redo",
            "Perform redo.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "task.analysis_update",
            "Alias of analysis.update: start tracked analysis and return task_id.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "task.search_text",
            "Start async search task.",
            {
                "session_id": {"type": "string"},
                "query": {"type": "string"},
                "limit": {"type": "integer", "minimum": 1},
            },
            ["session_id", "query"],
        ),
        _tool(
            "task.status",
            "Get task status.",
            {"task_id": {"type": "string"}},
            ["task_id"],
        ),
        _tool(
            "task.result",
            "Get terminal result (completed/failed/cancelled); pending tasks return an error.",
            {"task_id": {"type": "string"}},
            ["task_id"],
        ),
        _tool(
            "task.cancel",
            "Cancel pending/running work. Terminal tasks are unchanged; drain before reuse.",
            {"task_id": {"type": "string"}},
            ["task_id"],
        ),
        _tool(
            "database.create_bndb",
            "Create .bndb from session.",
            {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
            },
            ["session_id", "path"],
        ),
        _tool(
            "database.save_auto_snapshot",
            "Save auto snapshot.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "type.parse_string",
            "Parse a single type string.",
            {
                "session_id": {"type": "string"},
                "type_source": {"type": "string"},
                "import_dependencies": {"type": "boolean"},
            },
            ["session_id", "type_source"],
        ),
        _tool(
            "type.parse_declarations",
            "Parse C declarations for types/variables/functions.",
            {
                "session_id": {"type": "string"},
                "declarations": {"type": "string"},
                "options": {"type": "array", "items": {"type": "string"}},
                "include_dirs": {"type": "array", "items": {"type": "string"}},
                "import_dependencies": {"type": "boolean"},
            },
            ["session_id", "declarations"],
        ),
        _tool(
            "type.define_user",
            "Define user type from type source.",
            {
                "session_id": {"type": "string"},
                "type_source": {"type": "string"},
                "name": {"type": "string"},
                "import_dependencies": {"type": "boolean"},
            },
            ["session_id", "type_source"],
        ),
        _tool(
            "type.rename",
            "Rename a type.",
            {
                "session_id": {"type": "string"},
                "old_name": {"type": "string"},
                "new_name": {"type": "string"},
            },
            ["session_id", "old_name", "new_name"],
        ),
        _tool(
            "type.undefine_user",
            "Undefine a user type.",
            {"session_id": {"type": "string"}, "name": {"type": "string"}},
            ["session_id", "name"],
        ),
        _tool(
            "type.import_library_type",
            "Import type from type library.",
            {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "type_library_id": {"type": "string"},
            },
            ["session_id", "name"],
        ),
        _tool(
            "type.import_library_object",
            "Import object type from type library.",
            {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "type_library_id": {"type": "string"},
            },
            ["session_id", "name"],
        ),
        _tool(
            "type.export_to_library",
            "Export type into a type library.",
            {
                "session_id": {"type": "string"},
                "type_library_id": {"type": "string"},
                "type_source": {"type": "string"},
                "name": {"type": "string"},
                "import_dependencies": {"type": "boolean"},
            },
            ["session_id", "type_library_id", "type_source"],
        ),
        _tool(
            "type_library.create",
            "Create and optionally attach a type library.",
            {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "path": {"type": "string"},
                "add_to_view": {"type": "boolean"},
            },
            ["session_id", "name"],
        ),
        _tool(
            "type_library.load",
            "Load and optionally attach a type library.",
            {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "add_to_view": {"type": "boolean"},
            },
            ["session_id", "path"],
        ),
        _tool(
            "type_library.list",
            "List type libraries attached to the view.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "type_library.get",
            "Get one tracked type library.",
            {
                "session_id": {"type": "string"},
                "type_library_id": {"type": "string"},
            },
            ["session_id", "type_library_id"],
        ),
        _tool(
            "type_archive.create",
            "Create and optionally attach a type archive.",
            {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "platform_name": {"type": "string"},
                "attach": {"type": "boolean"},
            },
            ["session_id", "path"],
        ),
        _tool(
            "type_archive.open",
            "Open and optionally attach a type archive.",
            {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "attach": {"type": "boolean"},
            },
            ["session_id", "path"],
        ),
        _tool(
            "type_archive.list",
            "List attached type archives.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "type_archive.get",
            "Get one tracked type archive.",
            {
                "session_id": {"type": "string"},
                "type_archive_id": {"type": "string"},
            },
            ["session_id", "type_archive_id"],
        ),
        _tool(
            "type_archive.pull",
            "Pull types from a type archive.",
            {
                "session_id": {"type": "string"},
                "type_archive_id": {"type": "string"},
                "names": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            },
            ["session_id", "type_archive_id", "names"],
        ),
        _tool(
            "type_archive.push",
            "Push types to a type archive.",
            {
                "session_id": {"type": "string"},
                "type_archive_id": {"type": "string"},
                "names": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            },
            ["session_id", "type_archive_id", "names"],
        ),
        _tool(
            "type_archive.references",
            "Query archive incoming/outgoing references for one type.",
            {
                "type_archive_id": {"type": "string"},
                "name": {"type": "string"},
            },
            ["type_archive_id", "name"],
        ),
        _tool(
            "debug.parsers",
            "List debug info parsers valid for this view.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "debug.parse_and_apply",
            "Parse debug info and apply it to the view.",
            {
                "session_id": {"type": "string"},
                "debug_path": {"type": "string"},
                "parser_name": {"type": "string"},
            },
            ["session_id"],
        ),
        _tool("workflow.list", "List registered workflows."),
        _tool(
            "workflow.describe",
            "Describe workflow topology and settings.",
            {
                "session_id": {"type": "string"},
                "workflow_name": {"type": "string"},
                "activity": {"type": "string"},
                "immediate": {"type": "boolean"},
            },
            ["session_id"],
        ),
        _tool(
            "workflow.clone",
            "Clone workflow.",
            {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "register": {"type": "boolean"},
            },
            ["session_id", "name"],
        ),
        _tool(
            "workflow.insert",
            "Insert activities before an activity.",
            {
                "session_id": {"type": "string"},
                "workflow_name": {"type": "string"},
                "activity": {"type": "string"},
                "activities": {"type": ["array", "string"], "items": {"type": "string"}},
            },
            ["session_id", "activity", "activities"],
        ),
        _tool(
            "workflow.insert_after",
            "Insert activities after an activity.",
            {
                "session_id": {"type": "string"},
                "workflow_name": {"type": "string"},
                "activity": {"type": "string"},
                "activities": {"type": ["array", "string"], "items": {"type": "string"}},
            },
            ["session_id", "activity", "activities"],
        ),
        _tool(
            "workflow.remove",
            "Remove workflow activity.",
            {
                "session_id": {"type": "string"},
                "workflow_name": {"type": "string"},
                "activity": {"type": "string"},
            },
            ["session_id", "activity"],
        ),
        _tool(
            "workflow.graph",
            "Summarize workflow graph.",
            {
                "session_id": {"type": "string"},
                "workflow_name": {"type": "string"},
                "activity": {"type": "string"},
                "sequential": {"type": "boolean"},
            },
            ["session_id"],
        ),
        _tool(
            "workflow.machine.status",
            "Get workflow machine status.",
            {
                "session_id": {"type": "string"},
                "workflow_name": {"type": "string"},
            },
            ["session_id"],
        ),
        _tool(
            "workflow.machine.control",
            "Control workflow machine runtime.",
            {
                "session_id": {"type": "string"},
                "workflow_name": {"type": "string"},
                "action": {"type": "string"},
                "advanced": {"type": "boolean"},
                "incremental": {"type": "boolean"},
                "activities": {"type": ["array", "string"], "items": {"type": "string"}},
                "activity": {"type": "string"},
                "enable": {"type": "boolean"},
            },
            ["session_id", "action"],
        ),
        _tool(
            "il.rewrite.capabilities",
            "List IL rewrite support for one function and IL level.",
            {
                "session_id": {"type": "string"},
                "function_start": {"type": ["integer", "string"]},
                "level": {"type": "string"},
            },
            ["session_id", "function_start"],
        ),
        _tool(
            "il.rewrite.noop_replace",
            "Perform no-op IL expression replacement.",
            {
                "session_id": {"type": "string"},
                "function_start": {"type": ["integer", "string"]},
                "level": {"type": "string"},
                "index": {"type": "integer"},
                "finalize": {"type": "boolean"},
                "generate_ssa_form": {"type": "boolean"},
            },
            ["session_id", "function_start"],
        ),
        _tool(
            "il.rewrite.translate_identity",
            "Translate IL with identity mapping callback.",
            {
                "session_id": {"type": "string"},
                "function_start": {"type": ["integer", "string"]},
                "level": {"type": "string"},
            },
            ["session_id", "function_start"],
        ),
        _tool(
            "uidf.parse_possible_value",
            "Parse user-informed possible value set string.",
            {
                "session_id": {"type": "string"},
                "value": {"type": "string"},
                "state": {"type": "string"},
                "here": {"type": ["integer", "string"]},
            },
            ["session_id", "value", "state"],
        ),
        _tool(
            "uidf.set_user_var_value",
            "Set function user variable value.",
            {
                "session_id": {"type": "string"},
                "function_start": {"type": ["integer", "string"]},
                "variable_name": {"type": "string"},
                "def_addr": {"type": ["integer", "string"]},
                "value": {"type": "string"},
                "state": {"type": "string"},
                "after": {"type": "boolean"},
            },
            ["session_id", "function_start", "variable_name", "def_addr", "value", "state"],
        ),
        _tool(
            "uidf.clear_user_var_value",
            "Clear function user variable value.",
            {
                "session_id": {"type": "string"},
                "function_start": {"type": ["integer", "string"]},
                "variable_name": {"type": "string"},
                "def_addr": {"type": ["integer", "string"]},
                "after": {"type": "boolean"},
            },
            ["session_id", "function_start", "variable_name", "def_addr"],
        ),
        _tool(
            "uidf.list_user_var_values",
            "List all user variable values for a function.",
            {
                "session_id": {"type": "string"},
                "function_start": {"type": ["integer", "string"]},
            },
            ["session_id", "function_start"],
        ),
        _tool(
            "loader.rebase",
            "Rebase BinaryView.",
            {
                "session_id": {"type": "string"},
                "address": {"type": ["integer", "string"]},
                "force": {"type": "boolean"},
            },
            ["session_id", "address"],
        ),
        _tool(
            "loader.load_settings_types",
            "List loader settings type names.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "loader.load_settings_get",
            "Get loader settings values.",
            {
                "session_id": {"type": "string"},
                "type_name": {"type": "string"},
            },
            ["session_id", "type_name"],
        ),
        _tool(
            "loader.load_settings_set",
            "Set one loader setting value.",
            {
                "session_id": {"type": "string"},
                "type_name": {"type": "string"},
                "key": {"type": "string"},
                "value": {},
                "value_type": {"type": "string"},
            },
            ["session_id", "type_name", "key", "value"],
        ),
        _tool(
            "segment.add_user",
            "Add user segment.",
            {
                "session_id": {"type": "string"},
                "start": {"type": ["integer", "string"]},
                "length": {"type": "integer"},
                "data_offset": {"type": "integer"},
                "data_length": {"type": "integer"},
                "readable": {"type": "boolean"},
                "writable": {"type": "boolean"},
                "executable": {"type": "boolean"},
                "contains_data": {"type": "boolean"},
                "contains_code": {"type": "boolean"},
            },
            ["session_id", "start", "length"],
        ),
        _tool(
            "segment.remove_user",
            "Remove user segment.",
            {
                "session_id": {"type": "string"},
                "start": {"type": ["integer", "string"]},
                "length": {"type": "integer"},
            },
            ["session_id", "start"],
        ),
        _tool(
            "section.add_user",
            "Add user section.",
            {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "start": {"type": ["integer", "string"]},
                "length": {"type": "integer"},
                "semantics": {"type": "string"},
                "type_name": {"type": "string"},
                "align": {"type": "integer"},
                "entry_size": {"type": "integer"},
            },
            ["session_id", "name", "start", "length"],
        ),
        _tool(
            "section.remove_user",
            "Remove user section.",
            {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
            },
            ["session_id", "name"],
        ),
        _tool(
            "external.library_add",
            "Add external library.",
            {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "auto": {"type": "boolean"},
            },
            ["session_id", "name"],
        ),
        _tool(
            "external.library_list",
            "List external libraries.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "external.library_remove",
            "Remove external library.",
            {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
            },
            ["session_id", "name"],
        ),
        _tool(
            "external.location_add",
            "Add external location mapping.",
            {
                "session_id": {"type": "string"},
                "source_address": {"type": ["integer", "string"]},
                "library_name": {"type": "string"},
                "target_symbol": {"type": "string"},
                "target_address": {"type": ["integer", "string"]},
                "auto": {"type": "boolean"},
            },
            ["session_id", "source_address"],
        ),
        _tool(
            "external.location_get",
            "Get external location mapping.",
            {
                "session_id": {"type": "string"},
                "source_address": {"type": ["integer", "string"]},
            },
            ["session_id", "source_address"],
        ),
        _tool(
            "external.location_remove",
            "Remove external location mapping.",
            {
                "session_id": {"type": "string"},
                "source_address": {"type": ["integer", "string"]},
            },
            ["session_id", "source_address"],
        ),
        _tool(
            "arch.info",
            "Get architecture and platform metadata.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "arch.disasm_bytes",
            "Disassemble bytes with selected architecture.",
            {
                "session_id": {"type": "string"},
                "data_hex": {"type": "string"},
                "address": {"type": ["integer", "string"]},
                "arch_name": {"type": "string"},
            },
            ["session_id", "data_hex"],
        ),
        _tool(
            "arch.assemble",
            "Assemble instruction text with selected architecture.",
            {
                "session_id": {"type": "string"},
                "asm": {"type": "string"},
                "address": {"type": ["integer", "string"]},
                "arch_name": {"type": "string"},
            },
            ["session_id", "asm"],
        ),
        _tool(
            "transform.inspect",
            "Inspect/process transform pipeline. Requires session_id or path.",
            {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "mode": {"type": "string"},
                "process": {"type": "boolean"},
            },
        ),
        _tool(
            "project.create",
            "Create project.",
            {"path": {"type": "string"}, "name": {"type": "string"}},
            ["path", "name"],
        ),
        _tool(
            "project.open",
            "Open project.",
            {"path": {"type": "string"}},
            ["path"],
        ),
        _tool(
            "project.close",
            "Close tracked project.",
            {"project_id": {"type": "string"}},
            ["project_id"],
        ),
        _tool(
            "project.list",
            "List project folders/files.",
            {"project_id": {"type": "string"}},
            ["project_id"],
        ),
        _tool(
            "project.create_folder",
            "Create project folder.",
            {
                "project_id": {"type": "string"},
                "name": {"type": "string"},
                "parent_folder_id": {"type": "string"},
                "description": {"type": "string"},
            },
            ["project_id", "name"],
        ),
        _tool(
            "project.create_file",
            "Create project file from base64 data.",
            {
                "project_id": {"type": "string"},
                "name": {"type": "string"},
                "data_base64": {"type": "string"},
                "folder_id": {"type": "string"},
                "description": {"type": "string"},
            },
            ["project_id", "name", "data_base64"],
        ),
        _tool(
            "project.metadata_store",
            "Store project metadata.",
            {
                "project_id": {"type": "string"},
                "key": {"type": "string"},
                "value": {},
            },
            ["project_id", "key", "value"],
        ),
        _tool(
            "project.metadata_query",
            "Query project metadata.",
            {"project_id": {"type": "string"}, "key": {"type": "string"}},
            ["project_id", "key"],
        ),
        _tool(
            "project.metadata_remove",
            "Remove project metadata.",
            {"project_id": {"type": "string"}, "key": {"type": "string"}},
            ["project_id", "key"],
        ),
        _tool(
            "database.info",
            "Get database status for session.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
        _tool(
            "database.snapshots",
            "List database snapshots.",
            {
                "session_id": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            ["session_id"],
        ),
        _tool(
            "database.read_global",
            "Read database global string key.",
            {"session_id": {"type": "string"}, "key": {"type": "string"}},
            ["session_id", "key"],
        ),
        _tool(
            "database.write_global",
            "Write database global string key.",
            {
                "session_id": {"type": "string"},
                "key": {"type": "string"},
                "value": {"type": "string"},
            },
            ["session_id", "key", "value"],
        ),
        _tool(
            "plugin.valid_commands",
            "List context-valid plugin commands.",
            {
                "session_id": {"type": "string"},
                "address": {"type": ["integer", "string"]},
                "length": {"type": "integer"},
            },
            ["session_id"],
        ),
        _tool(
            "plugin.execute",
            "Execute a context-valid plugin command.",
            {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "address": {"type": ["integer", "string"]},
                "length": {"type": "integer"},
                "perform": {"type": "boolean"},
            },
            ["session_id", "name"],
        ),
        _tool("plugin_repo.status", "List plugin repositories and plugin states."),
        _tool(
            "plugin_repo.check_updates",
            "Check plugin repository updates.",
            {"perform": {"type": "boolean"}},
        ),
        _tool(
            "plugin_repo.plugin_action",
            "Run install/uninstall/enable/disable action on repository plugin.",
            {
                "repository_path": {"type": "string"},
                "plugin_path": {"type": "string"},
                "action": {"type": "string"},
            },
            ["repository_path", "plugin_path", "action"],
        ),
        _tool(
            "baseaddr.detect",
            "Run base-address detection.",
            {
                "session_id": {"type": "string"},
                "algorithm": {"type": "string", "enum": ["instruction", "sampling"]},
                "arch_name": {"type": "string"},
                "analysis": {"type": "string"},
                "min_strlen": {"type": "integer"},
                "alignment": {"type": "integer"},
                "low_boundary": {"type": "integer"},
                "high_boundary": {"type": "integer"},
                "max_pointers": {"type": "integer"},
            },
            ["session_id"],
        ),
        _tool(
            "baseaddr.reasons",
            "Get base-address detection reasons.",
            {
                "session_id": {"type": "string"},
                "base_address": {"type": ["integer", "string"]},
            },
            ["session_id", "base_address"],
        ),
        _tool(
            "baseaddr.abort",
            "Abort base-address detection.",
            {"session_id": {"type": "string"}},
            ["session_id"],
        ),
    ]


TOOL_DEFINITIONS = _definitions()

TOOL_DEFAULTS: dict[str, dict[str, Any]] = {
    "analysis.abort": {},
    "analysis.progress": {},
    "analysis.set_hold": {},
    "analysis.status": {},
    "analysis.update": {},
    "analysis.update_and_wait": {},
    "annotation.add_tag": {"icon": "M"},
    "annotation.define_data_var": {"name": None, "type_name": "char", "width": 1},
    "annotation.define_symbol": {"symbol_type": "FunctionSymbol"},
    "annotation.get_comment": {},
    "annotation.get_tags": {},
    "annotation.rename_data_var": {},
    "annotation.rename_function": {},
    "annotation.rename_symbol": {},
    "annotation.set_comment": {},
    "annotation.undefine_data_var": {},
    "annotation.undefine_symbol": {},
    "arch.assemble": {"address": 0, "arch_name": None},
    "arch.disasm_bytes": {"address": 0, "arch_name": None},
    "arch.info": {},
    "baseaddr.abort": {},
    "baseaddr.detect": {
        "algorithm": "instruction",
        "alignment": 1024,
        "analysis": "full",
        "arch_name": None,
        "high_boundary": 18446744073709551615,
        "low_boundary": 0,
        "max_pointers": 128,
        "min_strlen": 10,
    },
    "baseaddr.reasons": {},
    "binary.basic_blocks_at": {"limit": 100, "offset": 0},
    "binary.data_vars": {"limit": 100, "offset": 0},
    "binary.functions": {"limit": 100, "offset": 0},
    "binary.functions_at": {},
    "binary.get_function_at": {},
    "binary.get_function_disassembly_at": {},
    "binary.get_function_il_at": {"level": "mlil", "ssa": False},
    "binary.save": {},
    "binary.search_text": {"limit": 50},
    "binary.sections": {"limit": 100, "offset": 0},
    "binary.segments": {"limit": 100, "offset": 0},
    "binary.strings": {"limit": 100, "offset": 0},
    "binary.summary": {},
    "binary.symbols": {"limit": 100, "offset": 0},
    "binja.call": {"args": [], "kwargs": {}, "session_id": None},
    "binja.eval": {"session_id": None},
    "binja.info": {},
    "data.typed_at": {},
    "database.create_bndb": {},
    "database.info": {},
    "database.read_global": {},
    "database.save_auto_snapshot": {},
    "database.snapshots": {"limit": 100, "offset": 0},
    "database.write_global": {},
    "debug.parse_and_apply": {"debug_path": None, "parser_name": None},
    "debug.parsers": {},
    "disasm.function": {},
    "disasm.linear": {"limit": 200, "offset": 0},
    "disasm.range": {"limit": 200},
    "external.library_add": {"auto": False},
    "external.library_list": {},
    "external.library_remove": {},
    "external.location_add": {
        "auto": False,
        "library_name": None,
        "target_address": None,
        "target_symbol": None,
    },
    "external.location_get": {},
    "external.location_remove": {},
    "function.basic_blocks": {"limit": 100, "offset": 0},
    "function.callees": {},
    "function.callers": {},
    "function.metadata_query": {},
    "function.metadata_remove": {},
    "function.metadata_store": {},
    "function.ssa_memory_def_use": {"level": "mlil"},
    "function.ssa_var_def_use": {"level": "mlil"},
    "function.var_refs": {"level": "mlil"},
    "function.var_refs_from": {"length": None, "level": "mlil"},
    "function.variables": {},
    "health.ping": {},
    "il.address_to_index": {"level": "mlil", "ssa": False},
    "il.function": {"level": "mlil", "limit": 200, "offset": 0, "ssa": False},
    "il.index_to_address": {"level": "mlil", "ssa": False},
    "il.instruction_by_addr": {"level": "mlil", "ssa": False},
    "il.rewrite.capabilities": {"level": "mlil"},
    "il.rewrite.noop_replace": {
        "finalize": True,
        "generate_ssa_form": True,
        "index": None,
        "level": "mlil",
    },
    "il.rewrite.translate_identity": {"level": "mlil"},
    "loader.load_settings_get": {},
    "loader.load_settings_set": {"value_type": "string"},
    "loader.load_settings_types": {},
    "loader.rebase": {"force": False},
    "mcp.response_format": {},
    "memory.insert": {},
    "memory.read": {},
    "memory.reader_read": {"endian": "little"},
    "memory.remove": {},
    "memory.write": {},
    "memory.writer_write": {"endian": "little"},
    "metadata.query": {},
    "metadata.remove": {},
    "metadata.store": {},
    "patch.always_branch": {},
    "patch.assemble": {},
    "patch.convert_to_nop": {},
    "patch.invert_branch": {},
    "patch.never_branch": {},
    "patch.skip_and_return_value": {},
    "patch.status": {},
    "plugin.execute": {"address": None, "length": 0, "perform": False},
    "plugin.valid_commands": {"address": None, "length": 0},
    "plugin_repo.check_updates": {"perform": False},
    "plugin_repo.plugin_action": {},
    "plugin_repo.status": {},
    "project.close": {},
    "project.create": {},
    "project.create_file": {"description": "", "folder_id": None},
    "project.create_folder": {"description": "", "parent_folder_id": None},
    "project.list": {},
    "project.metadata_query": {},
    "project.metadata_remove": {},
    "project.metadata_store": {},
    "project.open": {},
    "search.all_constant": {"limit": 100},
    "search.all_data": {"limit": 100},
    "search.all_text": {"limit": 100, "regex": False},
    "search.data": {"end": None, "limit": 100, "start": None},
    "search.next_constant": {},
    "search.next_data": {},
    "search.next_text": {},
    "section.add_user": {
        "align": 1,
        "entry_size": 1,
        "semantics": "DefaultSectionSemantics",
        "type_name": "",
    },
    "section.remove_user": {},
    "segment.add_user": {
        "contains_code": False,
        "contains_data": True,
        "data_length": 0,
        "data_offset": 0,
        "executable": False,
        "readable": True,
        "writable": False,
    },
    "segment.remove_user": {"length": 0},
    "session.close": {},
    "session.list": {},
    "session.mode": {},
    "session.open": {
        "deterministic": True,
        "options": {},
        "read_only": True,
        "update_analysis": True,
    },
    "session.open_bytes": {
        "deterministic": True,
        "filename": "binary_ninja_headless_mcp_bytes.bin",
        "options": {},
        "read_only": True,
        "update_analysis": True,
    },
    "session.open_existing": {
        "deterministic": True,
        "options": {},
        "read_only": True,
        "update_analysis": False,
    },
    "session.set_mode": {"deterministic": None, "read_only": None},
    "task.analysis_update": {},
    "task.cancel": {},
    "task.result": {},
    "task.search_text": {"limit": 50},
    "task.status": {},
    "transform.inspect": {"mode": "full", "path": None, "process": False, "session_id": None},
    "type.define_user": {"import_dependencies": True, "name": None},
    "type.export_to_library": {"import_dependencies": True, "name": None},
    "type.import_library_object": {"type_library_id": None},
    "type.import_library_type": {"type_library_id": None},
    "type.parse_declarations": {"import_dependencies": True, "include_dirs": None, "options": None},
    "type.parse_string": {"import_dependencies": True},
    "type.rename": {},
    "type.undefine_user": {},
    "type_archive.create": {"attach": True, "platform_name": None},
    "type_archive.get": {},
    "type_archive.list": {},
    "type_archive.open": {"attach": True},
    "type_archive.pull": {},
    "type_archive.push": {},
    "type_archive.references": {},
    "type_library.create": {"add_to_view": True, "path": None},
    "type_library.get": {},
    "type_library.list": {},
    "type_library.load": {"add_to_view": True},
    "uidf.clear_user_var_value": {"after": True},
    "uidf.list_user_var_values": {},
    "uidf.parse_possible_value": {"here": None},
    "uidf.set_user_var_value": {"after": True},
    "undo.begin": {},
    "undo.commit": {"transaction_id": None},
    "undo.redo": {},
    "undo.revert": {"transaction_id": None},
    "undo.undo": {},
    "value.flags_at": {},
    "value.possible": {"level": "mlil", "ssa": False},
    "value.reg": {"after": False},
    "value.stack": {"after": False},
    "workflow.clone": {"register": False},
    "workflow.describe": {"activity": "", "immediate": True, "workflow_name": None},
    "workflow.graph": {"activity": "", "sequential": False, "workflow_name": None},
    "workflow.insert": {"workflow_name": None},
    "workflow.insert_after": {"workflow_name": None},
    "workflow.list": {},
    "workflow.machine.control": {
        "activities": None,
        "activity": None,
        "advanced": True,
        "enable": None,
        "incremental": False,
        "workflow_name": None,
    },
    "workflow.machine.status": {"workflow_name": None},
    "workflow.remove": {"workflow_name": None},
    "xref.code_refs_from": {"length": None},
    "xref.code_refs_to": {"limit": 100, "offset": 0},
    "xref.data_refs_from": {"length": None},
    "xref.data_refs_to": {"limit": 100},
}
